### ISSUE TITLE
vcf quality check

### ISSUE THREAD

**Issue by duncanjunegong** [chualec/HapChIP#2]
This issue is about https://github.com/chualec/HapChIP/blob/main/HapChIP/HapChIP_unit_tests.py
It is always good to ensure the quality of vcf as the input to HapChIP. You can use 'vcf-stats' and 'vcf-validator' from vcftools to check it as a part of unit test.
https://vcftools.github.io/perl_module.html

**Comment by chualec** [comment]
Quality assurance using vcftools will be added :)
