### ISSUE TITLE
Ben - feedback

### ISSUE THREAD

**Issue by benyli** [chualec/HapChIP#3]
Overall really nice job! I enjoyed learning about your project! I've provided some feedback below keeping with the recommended points in Homework 2, hope development is going well!

## Design documents
- DDS: clearly explained. Will the user be able to input preprocessed FASTQ or BAM files?
- SRS: related to the above, it seems like the package will perform QC and then some basic analysis. If I have an already-QC'ed file, will I have the option to just run that through the basic analysis?
- WBS: I really like how you have manageable tasks delineated so it is easy to edit and move through. Definitely something I am working on as well!
- WBS: As you work through your prototype, it might be helpful to add more detail to the steps needed to implement the prototype in your WBS

## Biological question
- It may be a good idea to include a link to a HiChIP review or easily-accessible summary for those less familiar with the technique. I found a paper with a nice summary and figure here (https://academic.oup.com/bioinformatics/article/36/12/3625/5811234). Are there other tools that do similar things to what you are proposing? What are their advantages and disadvantages? Very cool technique!

## Use of tools and resources discussed in class
- I liked how you used the drawio tool. It was a clear way of communicating your project parameters and I am going to try to add one to my project as well

## Feasibility of project
- I like how you have stepwise attainable goals for the project (QC) and also a stretch goal (basic HiChIP analysis) if you have time. I would be interested to see how these goals evolve in the coming weeks as you continue learning and get deeper into the project

## Progress
- There appears to have been progress made on the goals in the last week, particularly around adding more functions and unit tests

## Other
- I really liked how you included clear installation instructions!
- I recently switched from conda to mamba and highly recommend. Kelly has a nice summary in the Slack which I copied here as well
  > if you don’t already have a conda distribution installed, I highly recommended install the mambaforge distribution instead, as it comes with mamba already and you can just use mamba for everything rather than conda. https://github.com/conda-forge/miniforge#mambaforge
  > if you do already have a conda distro installed (e.g. anaconda3, miniconda3) and you don’t have any environments that you would be sad to lose, you can uninstall it (i.e. just delete the path to it) [I used the instructions here https://docs.anaconda.com/anaconda/install/uninstall/] and install mambaforge instead.

**Comment by chualec** [comment]
Thanks for the well-written feedback!
yes, preprocessed FASTQ or BAM files can also be used. There will be instructions on how to use those added
pre-QCed fastq/bam files should still undergo the library's QC to ensure no errors will happen :) but the QC is integrated into the script already, so there is no extra step for QC.
I can certainly add some information for current HiChIP analysis methods that other people have been using. So far there hasn't been other groups trying to do HiChIP and phasing together i think.
Mamba is something I am trying out as well :)
